
document.addEventListener('DOMContentLoaded', function () {
    var menuIcon = document.getElementById('menu-icon');
    var navMenu = document.querySelector('.nav-menu');
  
    menuIcon.addEventListener('click', function () {
      navMenu.style.display = (navMenu.style.display === 'flex') ? 'none' : 'flex';
  
      menuIcon.classList.toggle('opened');
      
      setTimeout(function() {
        menuIcon.innerHTML = (menuIcon.innerHTML === '☰') ? '✕' : '☰';
      }, 150);
    });
});
  
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 600) {
    document.getElementById("myBtn").style.display = "block";
  } else {
    document.getElementById("myBtn").style.display = "none";
  }
}

function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}

var popupData = {
    "exam-table-popup": {
        title: "Examination Table",
        description: "The examination table is where the patient lies during the scanning process. It is designed to slide in and out of the gantry, allowing the patient's body to be positioned correctly for imaging.",
    },

    "gantry-popup": {
        title: "Gantry",
        description: "The gantry is the large, donut-shaped part of the CT scanner that houses the X-ray tube and detectors. It is the most prominent feature of the CT scanner. The gantry can rotate around the patient to capture images from different angles.",
    },

    "vents-popup": {
        title: "Ventilation",
        description: "The cooling system helps to dissipate the heat generated by the X-ray tube and other components during operation, ensuring that the CT scanner functions correctly and safely.",
    },

    "control-popup": {
        title: "Control Room",
        description: "There is usually a separate control room adjacent to the CT room, where the radiologic technologist operates the scanner, monitors the patient, and adjusts the settings as needed.",
    },

    "walls-popup": {
        title: "Lead-lined Walls",
        description: "The walls of the CT room are lined with lead or other radiation-absorbing materials to prevent the escape of radiation and protect individuals outside the room.",
    },

    "lights-popup": {
        title: "Lights",
        description: "The room is well lit to create a safe and comfortable environment for both patients and staff.",
    },

    "floor-popup": {
        title: "Vinyl Flooring",
        description: "The flooring in a CT room is often made of vinyl or tile, which is easy to clean and maintain. This type of flooring is also durable and can withstand the weight of heavy equipment.",
    }
};

var detailsData = {
    "exam-table-popup-details": {
        title: "Examination Table Details",
        description: "The examination table of a computed tomography (CT) scanner is an important component of the imaging system, as it serves as the platform on which the patient is positioned during the scanning process.\n\nIt is designed to be comfortable, stable, and easily adjustable to accommodate patients of different sizes and conditions.\n\nHere are some additional details about the examination table of a CT scanner:\n\n1. Construction: The examination table is typically made of sturdy materials such as metal, plastic, or composite materials, which ensure its durability and stability. The table surface is usually covered with a cushioned pad or mattress to provide comfort to the patient during the scan.\n\n2. Adjustable Height: The examination table can be adjusted in height to allow for easy patient positioning and transfer. This feature is particularly important for patients who may have difficulty getting on and off the table, such as the elderly or those with mobility issues.\n\n3. Slide Mechanism: The table is equipped with a slide mechanism that allows it to move smoothly along the length of the scanner gantry. This movement is controlled by the CT technologist and is used to position the patient's body within the scanning area.\n\n4. Positioning Aids: The table may also include various positioning aids, such as straps, cushions, or blocks, which help to secure the patient in place and ensure proper alignment during the scan. These aids are used to minimize movement and ensure that the body part being scanned remains in the correct position throughout the scan.\n\n5. Weight Limit: CT examination tables have a maximum weight limit, which varies depending on the model and manufacturer. It is important to ensure that the patient's weight does not exceed this limit, as it could compromise the stability and safety of the table.\n\n6. Safety Features: The table may also include safety features such as emergency stop buttons, which allow the technologist or patient to halt the scan in case of an emergency. Additionally, the table is designed to be radiolucent, meaning it does not absorb or scatter the X-rays used in the CT scan, ensuring that the images are clear and accurate.",
        images: ["/images/exam-table.jpg"]
    },

    "gantry-popup-details": {
        title: "Gantry Details",
        description: "The gantry of a computed tomography (CT) scanner is a critical component of the imaging system, as it houses the X-ray tube and detectors and plays a key role in the acquisition of CT images. Here is a detailed description of the gantry of a CT scanner:\n\n1. Construction: The gantry is typically a large, circular or oval-shaped structure made of sturdy materials such as metal, plastic, or composites. It is designed to support and rotate the X-ray tube and detectors around the patient's body during the scanning process.\n\n2. Rotation Mechanism: The gantry is equipped with a rotation mechanism that allows it to rotate around the patient's body. This rotation is controlled by the CT technologist and is used to acquire multiple X-ray projections from different angles, which are then used to reconstruct the CT images.\n\n3. X-ray Tube: The X-ray tube is a critical component of the gantry, as it generates the X-rays used in the CT scan. The tube is mounted on the gantry and rotates around the patient's body, emitting X-rays that pass through the patient's body and are detected by the detectors on the opposite side of the gantry.\n\n4. Detectors: The detectors are mounted on the gantry opposite the X-ray tube and are used to detect the X-rays that pass through the patient's body. The detectors convert the X-ray energy into electrical signals, which are then used to reconstruct the CT images.\n\n5. Collimator: The collimator is a device mounted on the gantry that controls the size and shape of the X-ray beam emitted by the X-ray tube. It is used to minimize the exposure of radiation to the patient and ensure that only the area of interest is scanned.\n\n6. Slip Ring: The slip ring is a device that allows the gantry to rotate continuously around the patient's body. It is used in some CT scanners to acquire helical or spiral CT scans, where the gantry rotates continuously as the patient's body is moved through the scanner.\n\nOverall, the gantry of a CT scanner is a vital component of the imaging system, as it plays a crucial role in the acquisition of CT images by rotating the X-ray tube and detectors around the patient's body and acquiring multiple X-ray projections from different angles.",
        images: ["/images/gantry.jpg"]
    },

    "vents-popup-details": {
        title: "Ventilation Details",
        description: "Ventilation in a CT scan room is crucial to ensure a comfortable and safe environment for both patients and healthcare professionals. Here is a detailed description of the ventilation in a CT scan room:\n\n1. Air Exchange: The ventilation system in a CT scan room is designed to provide a sufficient number of air exchanges per hour to maintain good air quality and remove any contaminants or odors.\n\n2. Temperature Control: The ventilation system is also responsible for maintaining a comfortable temperature in the room, which is important for the comfort of the patients and the proper functioning of the CT scanner.\n\n3. Humidity Control: The ventilation system should also maintain an appropriate level of humidity in the room, as excessive humidity can affect the performance of the CT scanner and the comfort of the patients.\n\n4. Filtration: The ventilation system should include filters to remove dust, pollen, and other airborne particles from the air, ensuring a clean and healthy environment.\n\n5. Exhaust Fans: Exhaust fans are important for removing any fumes or odors that may be present in the room, especially if contrast agents or other chemicals are used during the scan.\n\n6. Air Quality Monitoring: Some CT scan rooms may also include air quality monitoring systems to continuously monitor the levels of pollutants and ensure that the air quality remains within acceptable limits.\n\nOverall, proper ventilation in a CT scan room is essential to maintain a safe and comfortable environment for both patients and healthcare professionals, and to ensure the optimal performance of the CT scanner.",
        images: ["/images/vents.jpg"]
    },

    "control-popup-details": {
        title: "Control Room Details",
        description: "The control room of a CT scanner is a critical component of the imaging system, as it serves as the workspace for the CT technologist who operates the scanner. Here is a detailed description of the control room of a CT scanner:\n\n1. Location: The control room is typically located adjacent to the CT scan room and is separated from it by a lead-lined window or wall to protect the technologist from radiation exposure.\n\n2. Workstation: The control room contains a workstation with a computer and monitor, where the CT technologist can operate the scanner, adjust the scanning parameters, and monitor the progress of the scan.\n\n3. Communication System: The control room is equipped with a communication system, such as an intercom or microphone, that allows the technologist to communicate with the patient during the scan.\n\n4. Radiation Shielding: The control room is designed with radiation shielding to protect the technologist from exposure to radiation during the scan. This may include lead-lined walls, windows, and doors.\n\n5. Storage: The control room may also include storage space for supplies, such as contrast agents, needles, syringes, and other materials needed for the scan.\n\n6. Monitoring Equipment: The control room may also be equipped with monitoring equipment, such as vital sign monitors and emergency equipment, to ensure the safety and well-being of the patient during the scan.\n\nOverall, the control room of a CT scanner is a vital component of the imaging system, as it provides a safe and functional workspace for the CT technologist to operate the scanner and monitor the patient during the scan.",
        images: ["/images/control-room.jpg"]
    },

    "walls-popup-details": {
        title: "Lead Lined Walls Details",
        description: "The walls of a CT scan room play a crucial role in ensuring the safety of patients and healthcare professionals by providing radiation protection. Here is a detailed description of the walls of a CT scan room:\n\n1. Lead Lining: The walls of a CT scan room are typically lined with lead or another radiation shielding material to prevent the spread of radiation outside the scan room.\n\n2. Thickness: The thickness of the lead lining in the walls depends on the energy of the X-rays used in the CT scanner, and is determined by local regulations and guidelines to ensure adequate radiation protection.\n\n3. Doors and Windows: The doors and windows of the CT scan room are also lined with lead or another radiation shielding material, and are designed to provide the same level of radiation protection as the walls.\n\n4. Surface Materials: The surface materials of the walls, such as paint or wall coverings, should be easy to clean and maintain, as the scan room must be kept clean and free of contaminants.\n\n5. Acoustics: The walls of the CT scan room may also be designed with acoustical properties to minimize noise and provide a quiet and comfortable environment for the patient during the scan.\n\n6. Structural Integrity: The walls of the CT scan room must be structurally sound and capable of supporting the weight of the lead lining and any other equipment or fixtures that may be mounted on them.\n\nOverall, the walls of a CT scan room are an essential component of the imaging system, as they provide the necessary radiation protection to ensure the safety of patients and healthcare professionals during the scan.",
        images: ["/images/lead-panel.jpg"]
    },

    "lights-popup-details": {
        title: "Lights Details",
        description: "Lighting in a CT scan room is an important aspect of creating a comfortable and functional environment for both patients and healthcare professionals. Here is a detailed description of the lighting in a CT scan room:\n\n1. Illuminance: The lighting in a CT scan room should provide sufficient illuminance to allow the healthcare professionals to perform their tasks accurately and safely. The level of illuminance required may vary depending on the specific tasks being performed.\n\n2. Color Temperature: The color temperature of the lighting should be chosen to create a comfortable and calming environment for the patient. Warm color temperatures are often preferred, as they can help to reduce anxiety and promote relaxation.\n\n3. Glare Control: The lighting should be designed to minimize glare and reflections, as glare can be distracting and uncomfortable for both patients and healthcare professionals.\n\n4. Task Lighting: Additional task lighting may be provided in specific areas of the scan room, such as the patient preparation area, to provide focused illumination for tasks that require more detailed attention.\n\n5. Dimmable Lights: The lights in the scan room may also be dimmable, allowing the healthcare professionals to adjust the lighting level to suit the specific needs of the patient and the procedure being performed.\n\n6. Emergency Lighting: Emergency lighting should be provided in the scan room to ensure that the room remains illuminated in the event of a power outage or other emergency.\n\nOverall, the lighting in a CT scan room is a key component of the imaging system, as it plays a crucial role in creating a comfortable and functional environment for both patients and healthcare professionals during the scan.",
        images: ["/images/lights.jpg"]
    },

    "floor-popup-details": {
        title: "Flooring Details",
        description: "The flooring in a CT scan room is an important aspect of creating a safe and functional environment for both patients and healthcare professionals. Here is a detailed description of the flooring in a CT scan room:\n\n1. Material: The flooring material should be durable and able to withstand heavy foot traffic and the weight of the CT scanner and other equipment. Common materials used for flooring in CT scan rooms include vinyl, linoleum, and rubber.\n\n2. Slip Resistance: The flooring should have slip-resistant properties to reduce the risk of slips and falls, especially in areas where the floor may become wet, such as the patient preparation area.\n\n3. Ease of Cleaning: The flooring material should be easy to clean and maintain, as the scan room must be kept clean and free of contaminants to ensure the safety and well-being of the patients and healthcare professionals.\n\n4. Comfort: The flooring should provide a comfortable surface for patients and healthcare professionals to walk and stand on, especially during long procedures.\n\n5. Conductivity: In some cases, the flooring may need to be electrically conductive or static dissipative to prevent the buildup of static electricity and protect sensitive electronic equipment.\n\n6. Aesthetics: The aesthetics of the flooring should be considered to create a visually pleasing environment for the patients and healthcare professionals.\n\nOverall, the flooring in a CT scan room is a critical component of the imaging system, as it plays a crucial role in creating a safe and functional environment for both patients and healthcare professionals during the scan.",
        images: ["/images/floor.jpg"]
    }    
};

function hidePopups() {
    var popups = [
        "exam-table-popup",
        "gantry-popup",
        "vents-popup",
        "control-popup",
        "walls-popup",
        "lights-popup",
        "floor-popup"
    ];

    for (var i = 0; i < popups.length; i++) {
        var popup = document.getElementById(popups[i]);
        popup.style.display = "none";
    }
}

function showPopup(targetPopupId, event) {
    var targetPopup = document.getElementById(targetPopupId);

    if (targetPopup.style.display === "block") {
        targetPopup.style.display = "none";
        return;
    }

    hidePopups();
    
    targetPopup.style.display = "block";
    var popupWidth = targetPopup.offsetWidth;
    var popupHeight = targetPopup.offsetHeight;
    var clickX = event.clientX + 15;
    var clickY = event.clientY + 15;
    var windowWidth = window.innerWidth;
    var windowHeight = window.innerHeight;

    if (clickX + popupWidth + 50 > windowWidth) {
        targetPopup.style.left = (windowWidth - popupWidth - 50) + "px";
    } else {
        targetPopup.style.left = clickX + "px";
    }
    if (clickY + popupHeight + 50 > windowHeight) {
        targetPopup.style.top = (windowHeight - popupHeight - 50) + "px";
    } else {
        targetPopup.style.top = clickY + "px";
    }

    targetPopup.querySelector(".popup-title").innerText = popupData[targetPopupId].title;
    targetPopup.querySelector(".popup-description").innerText = popupData[targetPopupId].description;
    targetPopup.querySelector(".popup-learn-more-link").addEventListener("click", function() {
        var basePopupId = targetPopupId.replace("-popup", "");
        var detailsPopupId = basePopupId + "-details";
        var detailsPopup = document.getElementById(detailsPopupId);
        console.log("Details popup ID:", detailsPopupId);
        console.log("Details popup element:", detailsPopup);
        if (detailsPopup) {
            detailsPopup.style.display = "block";
        } else {
            console.error("Details popup not found:", detailsPopupId);
        }
    });
}


function createPopup(popupId) {
    var popup = document.createElement("div");
    popup.classList.add("popup");
    popup.id = popupId;

    setPopupStyles(popup);

    var closeButton = document.createElement("button");
    closeButton.classList.add("popup-close-button");
    closeButton.innerText = "X";
    closeButton.style.position = "absolute";
    closeButton.style.top = "15px";
    closeButton.style.right = "15px";
    closeButton.style.fontSize = "1.3em";
    closeButton.style.background = "transparent";
    closeButton.style.border = "none";
    closeButton.style.cursor = "pointer";

    closeButton.addEventListener("click", function() {
        popup.style.display = "none";
    });

    popup.appendChild(closeButton);

    var popupContent = document.createElement("div");
    popupContent.classList.add("popup-content");

    var title = document.createElement("h2");
    title.classList.add("popup-title");

    setTitleStyles(popup);

    var description = document.createElement("p");
    description.classList.add("popup-description");

    setDescriptionStyles(popup);

    var learnMore = document.createElement("a");
    learnMore.classList.add("popup-learn-more-link");
    learnMore.innerText = "Learn More";
    learnMore.style.fontSize = "1em";
    learnMore.style.textTransform = "uppercase";
    learnMore.style.textDecoration = "none";
    learnMore.style.backgroundColor = "white";
    learnMore.style.borderRadius = "0.5em";
    learnMore.style.color = "darkred";
    learnMore.style.border = "1px solid darkred";
    learnMore.style.padding = "0.2em 0.5em";

    window.addEventListener("resize", function () {
        setPopupStyles(popup);
        setTitleStyles(popup);
        setDescriptionStyles(popup);
    });

    learnMore.addEventListener("mouseover", function() {
        learnMore.style.backgroundColor = "black";
        learnMore.style.color = "white";
        learnMore.style.border = "1px solid white";
    });

    learnMore.addEventListener("mouseout", function() {
        learnMore.style.backgroundColor = "white";
        learnMore.style.border = "1px solid darkred";
        learnMore.style.color = "darkred";
    });

    popupContent.appendChild(title);
    popupContent.appendChild(description);
    popupContent.appendChild(learnMore);

    popup.appendChild(popupContent);

    document.body.appendChild(popup);
}

function createDetailsPopup(basePopupId) {
    var detailsTitle = detailsData[basePopupId + "-popup-details"].title;
    var detailsDescription = detailsData[basePopupId + "-popup-details"].description;
    var detailsImages = detailsData[basePopupId + "-popup-details"].images;

    var detailsPopup = document.createElement("div");
    detailsPopup.classList.add("details-popup");
    detailsPopup.id = basePopupId + "-details";

    setDetailsPopupStyles(detailsPopup);

    var detailsContent = document.createElement("div");
    detailsContent.classList.add("details-content");

    var title = document.createElement("h2");
    title.classList.add("details-title");
    title.innerText = detailsTitle;

    setDetailsTitleStyles(title);

    var description = document.createElement("p");
    description.classList.add("details-description");
    
    description.innerText = detailsDescription;

    setDetailsDescriptionStyles(description);

    window.addEventListener("resize", function () {
        setDetailsPopupStyles(detailsPopup);
    });

    for (var i = 0; i < detailsImages.length; i++) {
        var image = document.createElement("img");
        image.src = detailsImages[i];
        image.style.width = "90%";
        image.style.display = "block";
        image.style.margin = "0 auto";
        image.style.padding = "1em";
        detailsContent.appendChild(image);
    }

    var closeButton = document.createElement("button");
    closeButton.classList.add("details-close-button");
    closeButton.style.fontSize = "1em";
    closeButton.style.textTransform = "uppercase";
    closeButton.style.padding = "0.5em 1em";
    closeButton.innerText = "Back";
    closeButton.addEventListener("click", function() {
        detailsPopup.style.display = "none";
    });

    detailsContent.appendChild(title);
    detailsContent.appendChild(description);
    detailsContent.appendChild(closeButton);

    detailsPopup.appendChild(detailsContent);

    document.body.appendChild(detailsPopup);
}

function setPopupStyles(popup) {
    if (window.innerWidth > 768) {
        popup.style.position = "absolute";
        popup.style.display = "none";
        popup.style.padding = "1.5em";
        popup.style.top = "10%";
        popup.style.left = "10%";
        popup.style.maxWidth = "80%";
    } else {
        popup.style.position = "absolute";
        popup.style.display = "none";
        popup.style.padding = "1em";
        popup.style.top = "5%";
        popup.style.left = "5%";
        popup.style.width = "70%";
    }

    popup.style.border = "1px solid black";
    popup.style.borderRadius = "2em";
    popup.style.backgroundColor = "rgba(255,255,255,0.9)";
    popup.style.zIndex = "100";
    popup.style.animation = "fadeIn 1s";
}

function setTitleStyles(title) {
    if (window.innerWidth > 768) {
        title.style.fontSize = "2em";
        title.style.fontWeight = "500";
        title.style.textTransform = "none";
    } else {
        title.style.fontSize = "1.5em";
        title.style.fontWeight = "500";
        title.style.textTransform = "none";
        title.style.fontWeight = "regular";
    }
    title.style.textAlign = "center";
    
}

function setDescriptionStyles(description) {
    if (window.innerWidth > 768) {
        description.style.fontSize = "1.2em";
        
    } else {
        description.style.fontSize = "1em";
    }
}


function setDetailsPopupStyles(detailsPopup) {
    if (window.innerWidth > 768) {
        detailsPopup.style.padding = "2em";
        detailsPopup.style.top = "5%";
        detailsPopup.style.bottom = "5%";
        detailsPopup.style.left = "5%";
        detailsPopup.style.right = "5%";
        detailsPopup.style.width = "80vw";
        detailsPopup.style.height = "80vh";
    } else {
        detailsPopup.style.padding = "1em";
        detailsPopup.style.top = "2%";
        detailsPopup.style.bottom = "2%";
        detailsPopup.style.left = "2%";
        detailsPopup.style.right = "2%";
        detailsPopup.style.width = "85vw";
        detailsPopup.style.height = "85vh";
    }

    detailsPopup.style.display = "none";
    detailsPopup.style.position = "fixed";
    detailsPopup.style.overflow = "auto";
    detailsPopup.style.border = "1px solid black";
    detailsPopup.style.borderRadius = "2em";
    detailsPopup.style.backgroundColor = "rgba(255,255,255,0.99)";
    detailsPopup.style.zIndex = "100";
    detailsPopup.style.animation = "fadeIn 1s";
}

function setDetailsTitleStyles(title) {
    if (window.innerWidth > 768) {
        title.style.fontSize = "2em";
    } else {
        title.style.fontSize = "1.5em";
    }

    title.style.textAlign = "center";
    title.style.fontWeight = "800";
    title.style.textTransform = "uppercase";
}

function setDetailsDescriptionStyles(description) {
    if (window.innerWidth > 768) {
        description.style.fontSize = "1.2em";
    } else {
        description.style.fontSize = "1em";
    }

    description.style.padding = "1em 0";
}


createPopup("exam-table-popup");
createPopup("gantry-popup");
createPopup("vents-popup");
createPopup("control-popup");
createPopup("walls-popup");
createPopup("lights-popup");
createPopup("floor-popup");

createDetailsPopup("exam-table");
createDetailsPopup("gantry");
createDetailsPopup("vents");
createDetailsPopup("control");
createDetailsPopup("walls");
createDetailsPopup("lights");
createDetailsPopup("floor");





var whatIsContent = document.createElement("div");
whatIsContent.style.fontSize = "1.2em";
whatIsContent.style.padding = "10em 5em";
whatIsContent.style.backgroundColor = "#f0ebeb";

var whatIsHeading = document.createElement("h1");
whatIsHeading.textContent = "Understanding Computed Tomography: A Window into the Human Body";
whatIsHeading.style.fontSize = "2.5em";
whatIsHeading.style.fontWeight = "400";
whatIsHeading.style.textTransform = "uppercase";
whatIsHeading.style.textAlign = "center";
whatIsHeading.style.padding = "2em";


var whatIsSubheading1 = document.createElement("h2");
whatIsSubheading1.textContent = "Introduction";
whatIsSubheading1.style.fontSize = "2em";
whatIsSubheading1.style.padding = "1em 0";

var whatIsParagraph1 = document.createElement("p");
whatIsParagraph1.textContent = "Computed Tomography (CT), also known as a CAT scan (Computerized Axial Tomography), is a medical imaging technique that revolutionized the field of diagnostic medicine. It provides detailed cross-sectional images of the body's internal structures, allowing healthcare professionals to visualize and analyze various tissues and organs with remarkable precision. This article explores the principles behind CT imaging, its applications, and its significance in modern healthcare.";
whatIsParagraph1.style.padding = "1em 0";
whatIsParagraph1.style.fontSize = "1.3em";


var whatIsSubheading2 = document.createElement("h2");
whatIsSubheading2.textContent = "Principles of Computed Tomography";
whatIsSubheading2.style.fontSize = "2em";
whatIsSubheading2.style.padding = "1em 0";


var whatIsParagraph2 = document.createElement("p");
whatIsParagraph2.textContent = "The fundamental principle of CT involves the use of X-rays to create detailed images of the body's interior. Unlike traditional X-ray imaging, which produces a single two-dimensional image, CT generates a series of cross-sectional images, or slices, of the body. These slices are then reconstructed by a computer to create a three-dimensional representation of the scanned area.";
whatIsParagraph2.style.padding = "1em 0";
whatIsParagraph2.style.fontSize = "1.3em";

var whatIsParagraph3 = document.createElement("p");
whatIsParagraph3.textContent = "The CT scanner consists of an X-ray tube that emits a narrow beam of X-rays, and a detector array that measures the radiation after it passes through the body. The patient lies on a motorized table, which moves through the scanner's circular opening. As the table advances, X-rays are directed through the body at different angles, producing a multitude of data points. The computer processes this data to create detailed images that reveal internal structures in unprecedented detail.";
whatIsParagraph3.style.padding = "1em 0";
whatIsParagraph3.style.fontSize = "1.3em";

var whatIsSubheading3 = document.createElement("h2");
whatIsSubheading3.textContent = "Applications of Computed Tomography";
whatIsSubheading3.style.fontSize = "2em";
whatIsSubheading3.style.padding = "1em 0";

var whatIsParagraph4 = document.createElement("p");
whatIsParagraph4.textContent = "CT imaging is a versatile tool used in various medical scenarios for both diagnostic and therapeutic purposes. Some common applications include:";
whatIsParagraph4.style.padding = "1em 0";
whatIsParagraph4.style.fontSize = "1.3em";



var whatIsUl = document.createElement("ul");

var whatIsLi1 = document.createElement("li");
whatIsLi1.textContent = "Diagnostic Imaging: CT scans are widely employed to diagnose and evaluate conditions affecting different parts of the body, such as the head, chest, abdomen, and pelvis. They are valuable in identifying abnormalities like tumors, fractures, infections, and vascular diseases.";
whatIsLi1.style.fontSize = "1.2em";
whatIsLi1.style.listStyleType = "decimal";
whatIsLi1.style.padding = "1.5em";


var whatIsLi2 = document.createElement("li");
whatIsLi2.textContent = "Cancer Detection and Staging: CT scans play a crucial role in cancer diagnosis by providing detailed images of tumors and helping determine their size, location, and extent. This information is vital for treatment planning and assessing the stage of the disease.";
whatIsLi2.style.fontSize = "1.2em";
whatIsLi2.style.padding = "1.5em";
whatIsLi2.style.listStyleType = "decimal";

var whatIsLi3 = document.createElement("li");
whatIsLi3.textContent = "Trauma and Emergency Medicine: In emergency situations, CT scans are instrumental in quickly assessing injuries, internal bleeding, and fractures, guiding healthcare professionals in making prompt and informed decisions.";
whatIsLi3.style.fontSize = "1.2em";
whatIsLi3.style.padding = "1.5em";
whatIsLi3.style.listStyleType = "decimal";

var whatIsLi4 = document.createElement("li");
whatIsLi4.textContent = "Guidance for Medical Procedures: CT imaging is often used to guide minimally invasive procedures such as biopsies, drainage of fluids, and needle aspirations. The precise visualization provided by CT helps ensure accuracy during these interventions.";
whatIsLi4.style.fontSize = "1.2em";
whatIsLi4.style.padding = "1.5em";
whatIsLi4.style.listStyleType = "decimal";

var whatIsLi5 = document.createElement("li");
whatIsLi5.textContent = "Monitoring and Follow-up: CT scans are valuable for monitoring the progress of treatments, such as cancer therapies, and for assessing the effectiveness of surgical interventions over time.";
whatIsLi5.style.fontSize = "1.2em";
whatIsLi5.style.padding = "1.5em";
whatIsLi5.style.listStyleType = "decimal";


var whatIsSubheading4 = document.createElement("h2");
whatIsSubheading4.textContent = "Benefits and Considerations";
whatIsSubheading4.style.fontSize = "2em";
whatIsSubheading4.style.padding = "1em 0";

var whatIsUl = document.createElement("ul");

var whatIsParagraph5 = document.createElement("p");
whatIsParagraph5.textContent = "While CT imaging offers unparalleled detail and diagnostic capabilities, it is essential to consider the potential risks associated with ionizing radiation exposure. Efforts are continually made to minimize radiation doses while maintaining diagnostic image quality. Additionally, alternative imaging modalities, such as magnetic resonance imaging (MRI) and ultrasound, are used when appropriate.";
whatIsParagraph5.style.padding = "1em 0";
whatIsParagraph5.style.fontSize = "1.3em";

var whatIsUl = document.createElement("ul");


var whatIsLi7 = document.createElement("li");
whatIsLi7.textContent = "High Resolution and Detailed Imaging: CT scans provide exceptionally detailed images of internal structures, allowing healthcare professionals to visualize tissues, organs, and abnormalities with a level of precision that is often unmatched by other imaging modalities. This high resolution is crucial for accurate diagnosis and treatment planning.";
whatIsLi7.style.fontSize = "1.2em";
whatIsLi7.style.listStyleType = "circle";
whatIsLi7.style.padding = "1.5em";

var whatIsLi8 = document.createElement("li");
whatIsLi8.textContent = "Versatility in Diagnostic Capabilities: Computed Tomography is versatile and can be applied to various areas of the body, including the head, chest, abdomen, and pelvis. This versatility makes it a valuable tool for diagnosing a wide range of medical conditions, from neurological disorders to vascular diseases and from trauma assessment to cancer detection.";
whatIsLi8.style.fontSize = "1.2em";
whatIsLi8.style.listStyleType = "circle";
whatIsLi8.style.padding = "1.5em";

var whatIsLi9 = document.createElement("li");
whatIsLi9.textContent = "Speed and Efficiency in Emergency Settings: In emergency medicine, time is often of the essence. CT scans offer rapid imaging capabilities, allowing healthcare professionals to quickly assess traumatic injuries, internal bleeding, and other critical conditions. The speed and efficiency of CT contribute significantly to prompt decision-making and timely interventions.";
whatIsLi9.style.fontSize = "1.2em";
whatIsLi9.style.listStyleType = "circle";
whatIsLi9.style.padding = "1.5em";

var whatIsLi10 = document.createElement("li");
whatIsLi10.textContent = "Guidance for Minimally Invasive Procedures: CT imaging plays a crucial role in guiding minimally invasive procedures, such as biopsies, drainage of fluids, and needle aspirations. The real-time visualization provided by CT ensures precision during these interventions, reducing the need for more invasive surgical procedures and promoting faster recovery times for patients.";
whatIsLi10.style.fontSize = "1.2em";
whatIsLi10.style.listStyleType = "circle";
whatIsLi10.style.padding = "1.5em";

var whatIsSubheading5 = document.createElement("h2");
whatIsSubheading5.textContent = "Conclusion";
whatIsSubheading5.style.fontSize = "2em";
whatIsSubheading5.style.padding = "1em 0"

var whatIsParagraph6 = document.createElement("p");
whatIsParagraph6.textContent = "Computed Tomography has become an indispensable tool in the realm of medical imaging, providing healthcare professionals with detailed insights into the human body's intricate structures. Its ability to diagnose and guide treatment across a spectrum of medical conditions has significantly improved patient care. As technology continues to advance, CT imaging is likely to evolve further, offering even greater precision and safety in the diagnosis and management of various health issues.";
whatIsParagraph6.style.padding = "1em 0";
whatIsParagraph6.style.fontSize = "1.3em";



whatIsContent.appendChild(whatIsHeading);
whatIsContent.appendChild(whatIsSubheading1);
whatIsContent.appendChild(whatIsParagraph1);
whatIsContent.appendChild(whatIsSubheading2);
whatIsContent.appendChild(whatIsParagraph2);
whatIsContent.appendChild(whatIsParagraph3);
whatIsContent.appendChild(whatIsSubheading3);
whatIsContent.appendChild(whatIsParagraph4);
whatIsContent.appendChild(whatIsUl);
whatIsContent.appendChild(whatIsLi1);
whatIsContent.appendChild(whatIsLi2);
whatIsContent.appendChild(whatIsLi3);
whatIsContent.appendChild(whatIsLi4);
whatIsContent.appendChild(whatIsLi5);
whatIsContent.appendChild(whatIsSubheading4);
whatIsContent.appendChild(whatIsUl);
whatIsContent.appendChild(whatIsLi7);
whatIsContent.appendChild(whatIsLi8);
whatIsContent.appendChild(whatIsLi9);
whatIsContent.appendChild(whatIsLi10);
whatIsContent.appendChild(whatIsParagraph5);
whatIsContent.appendChild(whatIsSubheading5);
whatIsContent.appendChild(whatIsParagraph6);

document.getElementById("what-is").appendChild(whatIsContent);


var howItWorksContent = document.createElement("div");
howItWorksContent.style.fontSize = "1.2em";
howItWorksContent.style.padding = "10em 5em";
howItWorksContent.style.backgroundColor = "#dadde8";

var howItWorksHeading = document.createElement("h1");
howItWorksHeading.textContent = "Unveiling the Inner Workings of Computed Tomography";
howItWorksHeading.style.fontSize = "2.5em";
howItWorksHeading.style.fontWeight = "400";
howItWorksHeading.style.textTransform = "uppercase";
howItWorksHeading.style.textAlign = "center";
howItWorksHeading.style.padding = "2em";

var howItWorksSubHeading1 = document.createElement("h2");
howItWorksSubHeading1.textContent = "Introduction";
howItWorksSubHeading1.style.fontSize = "2em";
howItWorksSubHeading1.style.padding = "1em 0";


var howItWorksParagraph1 = document.createElement("p");
howItWorksParagraph1.textContent = "In the realm of medical imaging, Computed Tomography (CT) stands as a groundbreaking technology, providing detailed insights into the human body's internal structures. But how does this marvel of modern medicine work? This article delves into the intricate process that powers CT imaging, exploring the principles and technologies that make it possible.";
howItWorksParagraph1.style.padding = "1em 0";
howItWorksParagraph1.style.fontSize = "1.3em";

var howItWorksSubHeading2 = document.createElement("h2");
howItWorksSubHeading2.textContent = "Principles of CT Imaging";
howItWorksSubHeading2.style.fontSize = "2em";
howItWorksSubHeading2.style.padding = "1em 0";

var howItWorksParagraph2 = document.createElement("p");
howItWorksParagraph2.textContent = "The cornerstone of CT imaging lies in its adept use of X-rays, a form of electromagnetic radiation. Unlike conventional X-ray techniques, which produce flat, two-dimensional images, CT scanners employ a sophisticated system to generate detailed three-dimensional representations of the body.";
howItWorksParagraph2.style.padding = "1em 0";
howItWorksParagraph2.style.fontSize = "1.3em";

var howItWorksUl = document.createElement("ul");

var howItWorksLi1 = document.createElement("li");
howItWorksLi1.textContent = "X-ray Emission: The CT process begins with the emission of a focused X-ray beam from a rotating tube. This tube revolves around the patient, emitting X-rays in a fan-shaped pattern. The emitted X-rays penetrate the body and are partially absorbed by the tissues they encounter.";
howItWorksLi1.style.fontSize = "1.2em";
howItWorksLi1.style.listStyleType = "upper-roman";
howItWorksLi1.style.padding = "1.5em";

var howItWorksLi2 = document.createElement("li");
howItWorksLi2.textContent = "Detectors: Positioned on the opposite side of the patient from the X-ray tube is a ring of detectors. These detectors pick up the X-rays that pass through the body. The amount of X-ray energy detected varies based on the density of the tissues encountered. Dense structures, such as bones, absorb more X-rays and appear brighter in the final image.";
howItWorksLi2.style.fontSize = "1.2em";
howItWorksLi2.style.listStyleType = "upper-roman";
howItWorksLi2.style.padding = "1.5em";

var howItWorksLi3 = document.createElement("li");
howItWorksLi3.textContent = "Data Acquisition: As the X-ray tube and detectors rotate around the patient, multiple projections are acquired from different angles. These projections are essentially a series of two-dimensional X-ray images. The data collected during this rotational process form the basis for creating cross-sectional images.";
howItWorksLi3.style.fontSize = "1.2em";
howItWorksLi3.style.listStyleType = "upper-roman";
howItWorksLi3.style.padding = "1.5em";

var howItWorksLi4 = document.createElement("li");
howItWorksLi4.textContent = "Computer Reconstruction: The acquired data is then sent to a computer, which employs complex mathematical algorithms to reconstruct cross-sectional images, or slices, of the scanned area. These slices represent thin sections of the body and can be further stacked to create a three-dimensional image.";
howItWorksLi4.style.fontSize = "1.2em";
howItWorksLi4.style.listStyleType = "upper-roman";
howItWorksLi4.style.padding = "1.5em";

var howItWorksSubHeading3 = document.createElement("h2");
howItWorksSubHeading3.textContent = "Applications of CT Technology:";
howItWorksSubHeading3.style.fontSize = "2em";
howItWorksSubHeading3.style.padding = "1em 0";

var howItWorksParagraph3 = document.createElement("p");
howItWorksParagraph3.textContent = "The versatility of CT technology extends across various medical domains, offering invaluable diagnostic capabilities in fields such as radiology, oncology, neurology, and emergency medicine. The detailed images produced by CT scans enable healthcare professionals to identify and assess conditions ranging from tumors and fractures to vascular abnormalities.";
howItWorksParagraph3.style.padding = "1em 0";
howItWorksParagraph3.style.fontSize = "1.3em";

var howItWorksUl1 = document.createElement("ul");

var howItWorksLi5 = document.createElement("li");
howItWorksLi5.textContent = "Accuracy and Precision: The detailed cross-sectional images generated by CT scans provide a level of accuracy and precision that is crucial for diagnosing complex medical conditions. This is particularly beneficial in surgical planning and guiding interventions.";
howItWorksLi5.style.fontSize = "1.2em";
howItWorksLi5.style.listStyleType = "square";
howItWorksLi5.style.padding = "1.5em";

var howItWorksLi6 = document.createElement("li");
howItWorksLi6.textContent = "Rapid Imaging: CT scanners can produce images quickly, making them highly suitable for emergency situations where timely assessment of traumatic injuries or acute conditions is vital for patient outcomes.";
howItWorksLi6.style.fontSize = "1.2em";
howItWorksLi6.style.listStyleType = "square";
howItWorksLi6.style.padding = "1.5em";

var howItWorksLi7 = document.createElement("li");
howItWorksLi7.textContent = "Non-Invasive Nature: CT imaging is non-invasive, eliminating the need for exploratory surgeries in many cases. This not only reduces patient discomfort but also minimizes recovery times.";
howItWorksLi7.style.fontSize = "1.2em";
howItWorksLi7.style.listStyleType = "square";
howItWorksLi7.style.padding = "1.5em";

var howItWorksLi8 = document.createElement("li");
howItWorksLi8.textContent = "Versatility Across Body Regions: CT's ability to scan various body regions makes it a versatile tool for diagnosing a wide range of medical conditions, from head to toe.";
howItWorksLi8.style.fontSize = "1.2em";
howItWorksLi8.style.listStyleType = "square";
howItWorksLi8.style.padding = "1.5em";

var howItWorksSubHeading4 = document.createElement("h2");
howItWorksSubHeading4.textContent = "Conclusion:";
howItWorksSubHeading4.style.fontSize = "2em";
howItWorksSubHeading4.style.padding = "1em 0";

var howItWorksParagraph4 = document.createElement("p");
howItWorksParagraph4.textContent = "Computed Tomography, with its blend of X-ray technology and advanced computer algorithms, has transformed the landscape of medical imaging. The ability to visualize the internal structures of the body with unparalleled detail has made CT an indispensable tool in the diagnosis and treatment of diverse medical conditions, enhancing patient care and contributing to advancements in healthcare.";
howItWorksParagraph4.style.padding = "1em 0";
howItWorksParagraph4.style.fontSize = "1.3em";


howItWorksContent.appendChild(howItWorksHeading);
howItWorksContent.appendChild(howItWorksSubHeading1);
howItWorksContent.appendChild(howItWorksParagraph1);
howItWorksContent.appendChild(howItWorksSubHeading2);
howItWorksContent.appendChild(howItWorksParagraph2);
howItWorksContent.appendChild(howItWorksUl);
howItWorksContent.appendChild(howItWorksLi1);
howItWorksContent.appendChild(howItWorksLi2);
howItWorksContent.appendChild(howItWorksLi3);
howItWorksContent.appendChild(howItWorksLi4);
howItWorksContent.appendChild(howItWorksSubHeading3);
howItWorksContent.appendChild(howItWorksParagraph3);
howItWorksContent.appendChild(howItWorksUl1);
howItWorksContent.appendChild(howItWorksLi5);
howItWorksContent.appendChild(howItWorksLi6);
howItWorksContent.appendChild(howItWorksLi7);
howItWorksContent.appendChild(howItWorksLi8);
howItWorksContent.appendChild(howItWorksSubHeading4);
howItWorksContent.appendChild(howItWorksParagraph4);

document.getElementById("how-it-works").appendChild(howItWorksContent);


var risksContent = document.createElement("div");
risksContent.style.fontSize = "1.2em";
risksContent.style.padding = "10em 5em";
risksContent.style.backgroundColor = "#e8dadb";


var risksHeading = document.createElement("h1");
risksHeading.textContent = "Navigating the Risks of Computed Tomography: Balancing Benefits and Concerns";
risksHeading.style.fontSize = "2.5em";
risksHeading.style.fontWeight = "400";
risksHeading.style.textTransform = "uppercase";
risksHeading.style.textAlign = "center";
risksHeading.style.padding = "2em";

var risksSubHeading1 = document.createElement("h2");
risksSubHeading1.textContent = "Introduction";
risksSubHeading1.style.fontSize = "2em";
risksSubHeading1.style.padding = "1em 0";

var risksParagraph1 = document.createElement("p");
risksParagraph1.textContent = "Computed Tomography (CT) has emerged as a powerful diagnostic tool, providing detailed images of internal structures within the human body. While CT scans offer valuable insights for healthcare professionals, it's essential to acknowledge and understand the potential risks associated with this imaging modality. This article explores the known risks of computed tomography, addressing concerns related to radiation exposure and other considerations.";
risksParagraph1.style.padding = "1em 0";
risksParagraph1.style.fontSize = "1.3em";

var risksUl = document.createElement("ul");

var risksLi1 = document.createElement("li");
risksLi1.textContent = "Ionizing Radiation Exposure: One of the primary concerns associated with CT scans is exposure to ionizing radiation. Unlike non-ionizing radiation used in imaging modalities such as ultrasound and magnetic resonance imaging (MRI), ionizing radiation has enough energy to remove tightly bound electrons from atoms, potentially causing damage to cellular structures. Prolonged or repeated exposure to ionizing radiation may increase the risk of developing cancer over time.";
risksLi1.style.fontSize = "1.2em";
risksLi1.style.listStyleType = "upper-latin";
risksLi1.style.padding = "1.5em";

var risksLi2 = document.createElement("li");
risksLi2.textContent = "Radiation Dose Variation: The amount of radiation a patient receives during a CT scan can vary based on factors such as the type of examination, the body part being scanned, and the scanning parameters selected by the operator. High doses of radiation are typically required for certain types of CT studies, raising concerns about cumulative exposure, especially in patients who require multiple scans over their lifetime.";
risksLi2.style.fontSize = "1.2em";
risksLi2.style.listStyleType = "upper-latin";
risksLi2.style.padding = "1.5em";

var risksLi3 = document.createElement("li");
risksLi3.textContent = "Risk-Benefit Analysis: It's crucial to emphasize that the benefits of obtaining critical diagnostic information through CT imaging often outweigh the potential risks, especially in cases where alternative imaging modalities may not provide sufficient detail. Healthcare professionals carefully consider the necessity of each CT scan, weighing the potential benefits against the associated radiation exposure.";
risksLi3.style.fontSize = "1.2em";
risksLi3.style.listStyleType = "upper-latin";
risksLi3.style.padding = "1.5em";

var risksLi4 = document.createElement("li");
risksLi4.textContent = "Special Considerations for Vulnerable Populations: Certain groups, such as pregnant women and children, are considered more sensitive to the effects of ionizing radiation. Pregnant women, in particular, are advised to avoid non-essential CT scans, especially during the first trimester, to minimize potential risks to the developing fetus. In pediatric imaging, efforts are made to optimize scanning parameters and limit radiation exposure whenever possible.";
risksLi4.style.fontSize = "1.2em";
risksLi4.style.listStyleType = "upper-latin";
risksLi4.style.padding = "1.5em";

var risksLi5 = document.createElement("li");
risksLi5.textContent = "Advancements in Technology: Continuous advancements in CT technology aim to reduce radiation doses while maintaining diagnostic image quality. Techniques such as iterative reconstruction and dose modulation contribute to minimizing the amount of radiation delivered during a scan. Healthcare providers are encouraged to stay informed about these technological developments to enhance patient safety.";
risksLi5.style.fontSize = "1.2em";
risksLi5.style.listStyleType = "upper-latin";
risksLi5.style.padding = "1.5em";


var risksSubHeading2 = document.createElement("h2");
risksSubHeading2.textContent = "Conclusion:";
risksSubHeading2.style.fontSize = "2em";
risksSubHeading2.style.padding = "1em 0";

var risksParagraph2 = document.createElement("p");
risksParagraph2.textContent = "While computed tomography has revolutionized diagnostic imaging, it is essential to approach it with a balanced perspective, considering both its benefits and associated risks. Awareness of potential radiation exposure and advancements in technology that mitigate these risks allows healthcare professionals to make informed decisions in the best interest of patient care. Open communication between healthcare providers and patients is key to ensuring that the benefits of CT imaging are maximized while minimizing potential risks, ultimately contributing to safer and more effective medical practices.";
risksParagraph2.style.padding = "1em 0";
risksParagraph2.style.fontSize = "1.3em";

risksContent.appendChild(risksHeading);
risksContent.appendChild(risksSubHeading1);
risksContent.appendChild(risksParagraph1);
risksContent.appendChild(risksUl);
risksContent.appendChild(risksLi1);
risksContent.appendChild(risksLi2);
risksContent.appendChild(risksLi3);
risksContent.appendChild(risksLi4);
risksContent.appendChild(risksLi5);
risksContent.appendChild(risksSubHeading2);
risksContent.appendChild(risksParagraph2);

document.getElementById("risks").appendChild(risksContent);


var faqContent = document.createElement("div");
faqContent.style.padding = "10em 5em";
faqContent.style.backgroundColor = "#e4e6d5";

var faqHeading = document.createElement("h1");
faqHeading.textContent = "Frequently Asked Questions about CT Scans";
faqHeading.style.fontSize = "2.5em";
faqHeading.style.fontWeight = "400";
faqHeading.style.textTransform = "uppercase";
faqHeading.style.textAlign = "center";
faqHeading.style.padding = "3em 1em";

faqContent.appendChild(faqHeading);

var faqItems = [
  { question: "What exactly happens during a CT scan?", answer: "During a CT scan, you will lie on a motorized table that moves through a circular opening in the scanner. The scanner emits X-rays, capturing multiple images from different angles. These images are then processed by a computer to create detailed cross-sectional views of the scanned area."},
  { question: "Why might my doctor recommend a CT scan instead of other imaging modalities?", answer: "Your doctor may choose a CT scan over other imaging methods based on the need for detailed, three-dimensional views. CT scans are particularly useful for evaluating complex structures, such as the brain, abdomen, and chest, where fine details are crucial for an accurate diagnosis."},
  { question: "Should I be concerned about radiation exposure during a CT scan?", answer: "While CT scans do involve exposure to X-ray radiation, the doses are generally considered safe for diagnostic purposes. Your healthcare provider will follow the ALARA principle (As Low As Reasonably Achievable) to minimize radiation exposure while obtaining the necessary diagnostic information."},
  { question: "Are there specific preparations I need to make before a CT scan?", answer: "Depending on the type of CT scan, your healthcare provider may ask you to refrain from eating or drinking for a few hours before the procedure. It's important to inform them of any allergies or existing medical conditions, as well as medications you are taking."},
  { question: "Can I have a CT scan if I'm pregnant?", answer: "If you are pregnant or suspect you might be, it's crucial to inform your healthcare provider before scheduling a CT scan. While some scans may be safe during pregnancy, precautions will be taken to minimize radiation exposure to the developing fetus."},
  { question: "What happens if I am allergic to contrast dye used in CT scans?", answer: "Contrast dye is sometimes used to enhance certain images during a CT scan. If you have a known allergy to contrast dye or iodine, inform your healthcare provider beforehand. They can take necessary precautions or explore alternative imaging methods if needed."},
  { question: "How long will the entire CT scan process take?", answer: "The duration of a CT scan varies, typically ranging from 15 to 30 minutes. Emergency situations may require quicker assessments, while more complex scans may take longer. Your healthcare provider will provide specific information based on your situation."},
  { question: "Will I receive the results immediately after the CT scan?", answer: "In most cases, the radiologist will analyze the images and provide a detailed report to your referring healthcare provider. The time it takes to receive results can vary, but your healthcare team will keep you informed about the process and any necessary follow-up appointments."},
  { question: "Are there any specific dietary restrictions after a CT scan?", answer: "Following a CT scan, you can generally resume normal activities and dietary habits unless your healthcare provider specifies otherwise. It's essential to follow any post-scan instructions provided by your healthcare team."},
  { question: "How often can I have CT scans, and are there long-term effects to consider?", answer: "The frequency of CT scans is determined by medical necessity, and your healthcare provider will carefully consider the benefits against potential risks. Routine or repeated scans are typically avoided unless medically necessary to minimize long-term effects of radiation exposure."},
];

faqItems.forEach(function (item, index) {
    var faqQuestion = document.createElement("h2");
    faqQuestion.textContent = item.question;
    faqQuestion.style.fontSize = "1.4em";
    faqQuestion.style.fontWeight = "300";
    faqQuestion.style.padding = "1em";
    faqQuestion.style.cursor = "pointer";
  
    var faqArrow = document.createElement("span");
    faqArrow.textContent = " ►";
    faqQuestion.appendChild(faqArrow);
  
    var faqAnswer = document.createElement("p");
    faqAnswer.textContent = item.answer;
    faqAnswer.style.fontSize = "1.3em";
    faqAnswer.style.padding = "1em";
    faqAnswer.style.display = "none";
  
  faqQuestion.addEventListener("click", function () {
    faqAnswer.style.display = (faqAnswer.style.display === "none") ? "block" : "none";
    faqArrow.textContent = (faqArrow.textContent === " ►") ? " ▼" : " ►";
  });

  faqContent.appendChild(faqQuestion);
  faqContent.appendChild(faqAnswer);

  if (index < faqItems.length - 1) {
    var line = document.createElement("hr");
    faqContent.appendChild(line);
  }
});

document.getElementById("faq").appendChild(faqContent);

function applyResponsiveStyles() {
    var windowWidth = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;

    if (windowWidth >= 768) {
        whatIsContent.style.padding = "5%";
        whatIsHeading.style.fontSize = "1.8em";
        whatIsHeading.style.padding = "1em";
        whatIsSubheading1.style.fontSize = "1.5em";
        whatIsParagraph1.style.fontSize = "1.2em";
        whatIsSubheading2.style.fontSize = "1.5em";
        whatIsParagraph2.style.fontSize = "1.2em";
        whatIsParagraph3.style.fontSize = "1.2em";
        whatIsSubheading3.style.fontSize = "1.5em";
        whatIsParagraph4.style.fontSize = "1.2em";
        whatIsLi1.style.fontSize = "1.1em";
        whatIsLi1.style.padding = "1em";
        whatIsLi2.style.fontSize = "1.1em";
        whatIsLi2.style.padding = "1em";
        whatIsLi3.style.fontSize = "1.1em";
        whatIsLi3.style.padding = "1em";
        whatIsLi4.style.fontSize = "1.1em";
        whatIsLi4.style.padding = "1em";
        whatIsLi5.style.fontSize = "1.1em";
        whatIsLi5.style.padding = "1em";
        whatIsSubheading4.style.fontSize = "1.5em";
        whatIsParagraph5.style.fontSize = "1.2em";
        whatIsLi7.style.fontSize = "1.1em";
        whatIsLi7.style.padding = "1em";
        whatIsLi8.style.fontSize = "1.1em";
        whatIsLi8.style.padding = "1em";
        whatIsLi9.style.fontSize = "1.1em";
        whatIsLi9.style.padding = "1em";
        whatIsLi10.style.fontSize = "1.1em";
        whatIsLi10.style.padding = "1em";
        whatIsSubheading5.style.fontSize = "1.5em";
        whatIsParagraph6.style.fontSize = "1.2em"

        howItWorksContent.style.padding = "1em";
        howItWorksHeading.style.fontSize = "1.8em";
        howItWorksSubHeading1.style.fontSize = "1.5em";
        howItWorksParagraph1.style.fontSize = "1.2em";
        howItWorksSubHeading2.style.fontSize = "1.5em";
        howItWorksParagraph2.style.fontSize = "1.2em";
        howItWorksLi1.style.padding = "1em";
        howItWorksLi1.style.fontSize = "1.1em";
        howItWorksLi2.style.padding = "1em";
        howItWorksLi2.style.fontSize = "1.1em";
        howItWorksLi3.style.padding = "1em";
        howItWorksLi3.style.fontSize = "1.1em";
        howItWorksLi4.style.padding = "1em";
        howItWorksLi4.style.fontSize = "1.1em";
        howItWorksSubHeading3.style.fontSize = "1.5em";
        howItWorksParagraph3.style.fontSize = "1.2em";
        howItWorksLi5.style.padding = "1em";
        howItWorksLi5.style.fontSize = "1.1em";
        howItWorksLi6.style.padding = "1em";
        howItWorksLi6.style.fontSize = "1.1em";
        howItWorksLi7.style.padding = "1em";
        howItWorksLi7.style.fontSize = "1.1em";
        howItWorksLi8.style.padding = "1em";
        howItWorksLi8.style.fontSize = "1.1em";
        howItWorksSubHeading4.style.fontSize = "1.5em";
        howItWorksParagraph4.style.fontSize = "1.2em";

        risksContent.style.padding = "1em";
        risksHeading.style.fontSize = "1.8em";
        risksSubHeading1.style.fontSize = "1.5em";
        risksParagraph1.style.fontSize = "1.2em";
        risksLi1.style.fontSize = "1.1em";
        risksLi1.style.padding = "1em";
        risksLi2.style.fontSize = "1.1em";
        risksLi2.style.padding = "1em";
        risksLi3.style.fontSize = "1.1em";
        risksLi3.style.padding = "1em";
        risksLi4.style.fontSize = "1.1em";
        risksLi4.style.padding = "1em";
        risksLi5.style.fontSize = "1.1em";
        risksLi5.style.padding = "1em";
        risksSubHeading2.style.fontSize = "1.5em";
        risksParagraph2.style.fontSize = "1.2em";

        faqContent.style.padding = "1em";
        faqHeading.style.fontSize = "1.8em";

    } else if (windowWidth < 768) {
        
        whatIsContent.style.padding = "3%";
        whatIsHeading.style.fontSize = "1.3em";
        whatIsHeading.style.padding = "1em";
        whatIsSubheading1.style.fontSize = "1.2em";
        whatIsParagraph1.style.fontSize = "1em";
        whatIsSubheading2.style.fontSize = "1.2em";
        whatIsParagraph2.style.fontSize = "1em";
        whatIsParagraph3.style.fontSize = "1em";
        whatIsSubheading3.style.fontSize = "1.2em";
        whatIsParagraph4.style.fontSize = "1em";
        whatIsLi1.style.fontSize = "1em";
        whatIsLi1.style.padding = "1em";
        whatIsLi2.style.fontSize = "1em";
        whatIsLi2.style.padding = "1em";
        whatIsLi3.style.fontSize = "1em";
        whatIsLi3.style.padding = "1em";
        whatIsLi4.style.fontSize = "1em";
        whatIsLi4.style.padding = "1em";
        whatIsLi5.style.fontSize = "1em";
        whatIsLi5.style.padding = "1em";
        whatIsSubheading4.style.fontSize = "1.2em";
        whatIsParagraph5.style.fontSize = "1em";
        whatIsLi7.style.fontSize = "1em";
        whatIsLi7.style.padding = "1em";
        whatIsLi8.style.fontSize = "1em";
        whatIsLi8.style.padding = "1em";
        whatIsLi9.style.fontSize = "1em";
        whatIsLi9.style.padding = "1em";
        whatIsLi10.style.fontSize = "1em";
        whatIsLi10.style.padding = "1em";
        whatIsSubheading5.style.fontSize = "1.2em";
        whatIsParagraph6.style.fontSize = "1em"

        howItWorksContent.style.padding = "1em";
        howItWorksHeading.style.fontSize = "1.3em";
        howItWorksSubHeading1.style.fontSize = "1.2em";
        howItWorksParagraph1.style.fontSize = "1em";
        howItWorksSubHeading2.style.fontSize = "1.2em";
        howItWorksParagraph2.style.fontSize = "1em";
        howItWorksLi1.style.padding = "1em";
        howItWorksLi1.style.fontSize = "1em";
        howItWorksLi2.style.padding = "1em";
        howItWorksLi2.style.fontSize = "1em";
        howItWorksLi3.style.padding = "1em";
        howItWorksLi3.style.fontSize = "1em";
        howItWorksLi4.style.padding = "1em";
        howItWorksLi4.style.fontSize = "1em";
        howItWorksSubHeading3.style.fontSize = "1.2em";
        howItWorksParagraph3.style.fontSize = "1em";
        howItWorksLi5.style.padding = "1em";
        howItWorksLi5.style.fontSize = "1em";
        howItWorksLi6.style.padding = "1em";
        howItWorksLi6.style.fontSize = "1em";
        howItWorksLi7.style.padding = "1em";
        howItWorksLi7.style.fontSize = "1em";
        howItWorksLi8.style.padding = "1em";
        howItWorksLi8.style.fontSize = "1em";
        howItWorksSubHeading4.style.fontSize = "1.2em";
        howItWorksParagraph4.style.fontSize = "1em";

        risksContent.style.padding = "1em";
        risksHeading.style.fontSize = "1.3em";
        risksSubHeading1.style.fontSize = "1.2em";
        risksParagraph1.style.fontSize = "1em";
        risksLi1.style.fontSize = "1em";
        risksLi1.style.padding = "1em";
        risksLi2.style.fontSize = "1em";
        risksLi2.style.padding = "1em";
        risksLi3.style.fontSize = "1em";
        risksLi3.style.padding = "1em";
        risksLi4.style.fontSize = "1em";
        risksLi4.style.padding = "1em";
        risksLi5.style.fontSize = "1em";
        risksLi5.style.padding = "1em";
        risksSubHeading2.style.fontSize = "1.2em";
        risksParagraph2.style.fontSize = "1em";

        faqContent.style.padding = "1em";
        faqHeading.style.fontSize = "1.5em";
    } else if (windowWidth >= 1280) {}
}

applyResponsiveStyles();

window.addEventListener("resize", applyResponsiveStyles);